---
- name: Supprime les doublons dans un fichier CSV
  hosts: localhost
  gather_facts: no
  tasks:
    - name: Lit le CSV
      community.general.read_csv:
        path: temperature.csv
        delimiter: ','
      register: csv_data
      delegate_to: localhost

    - name: Supprime les doublons
      set_fact:
        unique_data: "{{ csv_data.list | unique }}"
      delegate_to: localhost

    - name: Ecrit les data uniques dans un nouveau fichier
      copy:
        content: |
          time,temperature
          {% for item in unique_data %}
          {{ item.time }},{{ item.temperature }}
          {% endfor %}
        dest: temperature_sans_doublons.csv
      delegate_to: localhost

