---
- name: Installe et configure les logiciels sur les machines cibles
  hosts: all
  become: yes
  tasks:
    - name: Mettre à jour la liste des paquets (apt)
      ansible.builtin.apt:
        update_cache: yes
      when: ansible_os_family == 'Debian'

- name: Installe les softs sur les machines web (Ubuntu 22.04)
  hosts: web
  become: yes
  tasks:
    - name: Installe les paquets pour les serveurs web
      ansible.builtin.apt:
        name: "{{ item }}"
        state: present
      loop:
        - apache2
        - mysql-server

- name: Installe les softs sur la machine de dev (Debian 12)
  hosts: dev
  become: yes
  tasks:
    - name: Installe les paquets pour la machine de dev
      ansible.builtin.apt:
        name: "{{ item }}"
        state: present
      loop:
        - git
        - nginx
        - cowsay

