---
- name: Installe et configure les softs sur les machines cibles
  hosts: all
  tasks:

    - name: Installe les softs sur les machines web (Ubuntu 22.04)
      ansible.builtin.apt:
        name: "{{ item }}"
        state: present
        update_cache: yes
      loop:
        - apache2
        - mysql-server
      when: ansible_os_family == 'Ubuntu'

    - name: Installe les paquets pour la machine de dev
      ansible.builtin.apt:
        name: "{{ item }}"
        state: present
        update_cache: yes
      loop:
        - git
        - nginx
        - cowsay
      when: ansible_os_family == 'Debian'

    - name: Installe les softs sur les machines web (Ubuntu 22.04)
      ansible.builtin.apt:
        name: ufw
        state: present
      when: ansible_os_family == 'Ubuntu'
