---
- name: Installe et configure les softs sur les machines cibles
  hosts: all
  tasks:

    - name: Installe les softs sur les machines web (Ubuntu 22.04)
      ansible.builtin.apt:
        name: "{{ item }}"
        state: present
        update_cache: yes
      loop:
        - apache2
        - mysql-server
      when: ansible_os_family == 'Ubuntu'

    - name: Installe les paquets pour la machine de dev
      ansible.builtin.apt:
        name: "{{ item }}"
        state: present
        update_cache: yes
      loop:
        - git
        - nginx
        - cowsay
      when: ansible_os_family == 'Debian'

    - name: Installe les softs sur les machines web (Ubuntu 22.04)
      ansible.builtin.apt:
        name: ufw
        state: present
      when: ansible_os_family == 'Ubuntu'

    - name: Gather the rpm package facts
      ansible.builtin.package_facts:
        manager: auto

    - name: Copy index.html if apache2 or nginx is installed
      ansible.builtin.template:
        src: template/index.j2
        dest: /var/www/html/index.html
        mode: '0644'
      when: "'apache2' in ansible_facts.packages or 'nginx' in ansible_facts.packages"

    - name: Start apache2
      ansible.builtin.service:
        name: apache2
        state: started
      when: "'apache2' in ansible_facts.packages"

    - name: Start nginx
      ansible.builtin.service:
        name: nginx
        state: started
      when: "'nginx' in ansible_facts.packages"    
