- name: Instal et verif service apache2
  hosts: all
  remote_user: root

  tasks:
  - name: Update cache & Install apache2
    ansible.builtin.apt:
      update_cache: yes
      name: apache2
      state: present

  - name: Start apache2
    ansible.builtin.service:
      state: started
      name: apache2

  - name: Install mysql-server
    ansible.builtin.apt:
    name: mysql-server
    state: present
