---
- name : Install DB
  hosts: db

  vars:
    mysql_root_password: 1234
    mysql_databases:
        - name: DBtest
          encoding: latin1
          collation: latin1_general_ci
    mysql_users:
        - name: user1
          host: "%"
          password: 1234
          priv: "DBtest.*:ALL"

  roles:
    - geerlingguy.mysql


- name: Unarchive a file that needs to be downloaded 
  hosts: web
  vars:
    php_packages_extra:
      - php-mysql

    php_enable_php_fpm: true

    apache_listen_port: 8080
    apache_remove_default_vhost: true
    apache_create_vhosts: true
    apache_vhosts:
      - servername: "wordpress.local"
        documentroot: "/var/www/wordpress/"
        extra_parameters: |
          ProxyPassMatch ^/(.*\.php(/.*)?)$ "fcgi://127.0.0.1:9000/var/www/wordpress"

  roles:
    - geerlingguy.apache
    - geerlingguy.php
    - geerlingguy.apache-php-fpm

  tasks: 
    - name: uncompress wordpress
      ansible.builtin.unarchive:
        src: https://fr.wordpress.org/wordpress-6.8.3-fr_FR.tar.gz
        dest: /var/www
        remote_src: true



    - name: Configure wordpress wp-config.php
      ansible.builtin.template:
        src: templates/wp-config.j2
        dest: /var/www/wordpress/wp-config.php
        mode: '0644'

